# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='location',
            field=models.CharField(choices=[('pnw', 'Pacific Northwest'), ('ne', 'New England'), ('ma', 'Mid-Atlantic'), ('se', 'Southeast'), ('mw', 'Midwest'), ('ds', 'Deep South'), ('sw', 'Southwest'), ('cf', 'California'), ('ak', 'Alaska'), ('hi', 'Hawaii')], max_length=3),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='photography_type',
            field=models.CharField(choices=[('portrait', 'Portrait Photography'), ('nature', 'Nature Photography'), ('sports', 'Sports Photography')], max_length=255),
        ),
    ]
