# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 22:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0003_auto_20160421_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='friend_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='location',
            field=models.CharField(choices=[('pnw', 'Pacific Northwest'), ('ne', 'New England'), ('ma', 'Mid-Atlantic'), ('se', 'Southeast'), ('mw', 'Midwest'), ('ds', 'Deep South'), ('sw', 'Southwest'), ('cf', 'California'), ('ak', 'Alaska'), ('hi', 'Hawaii')], max_length=3, null=True),
        ),
    ]
