# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 22:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0004_auto_20160421_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
