# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0005_auto_20160421_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='location',
            field=models.CharField(blank=True, choices=[('pnw', 'Pacific Northwest'), ('ne', 'New England'), ('ma', 'Mid-Atlantic'), ('se', 'Southeast'), ('mw', 'Midwest'), ('ds', 'Deep South'), ('sw', 'Southwest'), ('cf', 'California'), ('ak', 'Alaska'), ('hi', 'Hawaii')], max_length=3, null=True),
        ),
    ]
