# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 08:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cover_photo', to='imager_images.Photo'),
        ),
        migrations.AddField(
            model_name='album',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 12, 8, 41, 9, 184355, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 12, 8, 41, 19, 327359, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 12, 8, 41, 25, 692274, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='published',
            field=models.CharField(choices=[('private', 'private'), ('shared', 'shared'), ('public', 'public')], default='private', max_length=255),
        ),
        migrations.AddField(
            model_name='album',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='photo_files/%Y-%m-%d'),
        ),
        migrations.AddField(
            model_name='photo',
            name='photos',
            field=models.ManyToManyField(related_name='photos', to='imager_images.Album'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
