# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0006_auto_20160413_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='albums',
            field=models.ManyToManyField(null=True, related_name='photos', to='imager_images.Album'),
        ),
    ]
