# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0007_auto_20160414_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='albums',
        ),
        migrations.AddField(
            model_name='album',
            name='pictures',
            field=models.ManyToManyField(null=True, related_name='photos', to='imager_images.Photo'),
        ),
    ]
