# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0010_auto_20160417_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='cover_photo',
        ),
        migrations.AddField(
            model_name='album',
            name='cover_photo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='imager_images.Photo'),
        ),
    ]
