# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0011_auto_20160417_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='pictures',
            field=models.ManyToManyField(blank=True, related_name='photos', to='imager_images.Photo'),
        ),
    ]
